version: '3.8'

services:
  # Backend Service
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: energyhive-backend
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - MONGODB_URL=mongodb+srv://myAtlasDBUser:admin@driverdetails.apcoi.mongodb.net/?retryWrites=true&w=majority&appName=DriverDetails
      - MAILTRAP_USER=api
      - MAILTRAP_PASS=73697db3b188fd827124cbb1d7daf553
    volumes:
      - ./backend/pdfs:/app/pdfs
    restart: unless-stopped
    networks:
      - energyhive-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Frontend Service
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: energyhive-frontend
    ports:
      - "80:80"
    depends_on:
      - backend
    restart: unless-stopped
    networks:
      - energyhive-network

  # MongoDB (optional local instance)
  # mongodb:
  #   image: mongo:6
  #   container_name: energyhive-mongodb
  #   ports:
  #     - "27017:27017"
  #   environment:
  #     MONGO_INITDB_ROOT_USERNAME: admin
  #     MONGO_INITDB_ROOT_PASSWORD: password
  #   volumes:
  #     - mongodb_data:/data/db
  #   restart: unless-stopped
  #   networks:
  #     - energyhive-network

networks:
  energyhive-network:
    driver: bridge

volumes:
  mongodb_data: