jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install dependencies
        working-directory: ./backend
        run: npm install

      - name: Start backend server
        working-directory: ./backend
        run: |
          # Start server in background
          nohup npm start &
          # Wait for the server to be ready (adjust wait time if needed)
          sleep 10

      - name: Run Postman collection via npm script
        working-directory: ./backend
        run: npm run test:api1
