name: Run API Tests

on:
  push:
    branches: [pranshu]
  pull_request:
    branches: [pranshu]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install dependencies
        working-directory: ./backend
        run: npm install

      - name: Run Postman collection via npm script
        working-directory: ./backend
        run: npm run test:api1
